version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - misspell
    - ineffassign
    - gocritic
    - gosec
    - errorlint
    - nolintlint
  exclusions:
    paths:
      - "dist/"

formatters:
  enable:
    - gofmt
