version: 2

builds:
  - id: installer
    dir: extras/installer
    binary: cco
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: statusline
    dir: extras/statusline
    binary: cco-statusline
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: installer
    builds: [installer]
    format: binary
    name_template: "cco-{{ .Os }}-{{ .Arch }}"
  - id: statusline
    builds: [statusline]
    format: binary
    name_template: "cco-statusline-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums-sha256.txt
  algorithm: sha256

release:
  mode: append

changelog:
  disable: true
